#!/bin/bash
cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch styx_Z01R-userdebug

make_metalava(){
	mka api-stubs-docs
	mka system-api-stubs-docs
	mka test-api-stubs-docs
}

make_rom(){
	m styx-ota -j16
	zip=$(up out/target/product/Z01R/*zip)
	echo " "
	echo "$zip"
}

make_metalava
make_rom
