#!/bin/bash

MANIFEST=git://github.com/Evolution-X/manifest.git
BRANCH=elle

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Aryan Arora"
git config --global user.email arora.aryan7@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
git clone https://github.com/AruAA/android_device_asus_Z01R-2.git --single-branch -b evo device/asus/Z01R --depth=1
git clone https://github.com/5z-devs/proprietary_vendor_asus.git --single-branch -b lineage-18.1 vendor/asus --depth=1
git clone https://github.com/kailashrs/kernel_z01r.git --single-branch -b eleven kernel/asus/sdm845 --depth=1
git clone https://github.com/AOSPA/android_prebuilts_gcc_linux-x86_aarch64_aarch64-elf --single-branch -b master prebuilts/gcc/linux-x86/aarch64/aarch64-elf --depth=1
git clone https://www.github.com/AOSPA/android_prebuilts_gcc_linux-x86_arm_arm-eabi --single-branch -b master prebuilts/gcc/linux-x86/arm/arm-eabi --depth=1
