#!/bin/bash

MANIFEST=git://github.com/StyxProject/manifest.git
BRANCH=R

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "Sandeep Sethi"
git config --global user.email adeveloper79@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Sync stuffs
git clone https://gitlab.com/adeveloper79/r_z01r.git device/asus/Z01R --depth=1
git clone https://github.com/5z-devs/proprietary_vendor_asus.git --single-branch -b 11 vendor/asus --depth=1
git clone https://github.com/BlissRoms-Devices/android_kernel_asus_sdm845.git kernel/asus/sdm845 --depth=1
